# Generated by Django 2.2.5 on 2019-09-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
